activation: silu
aggr: add
atom_filter: -1
attn_activation: silu
batch_size: 128
cutoff_lower: 0.0
cutoff_upper: 6.0

use_clip: false
use_cloob: true
pretrain_atom_only: false
pretrain_mol_only: true


transfer_learning: false
fine_tuning: false

dataset: QM7X_clip
dataset_root: /Users/jnc/Documents/torchmd-clip
dataset_arg: all_props

distance_influence: both
distributed_backend: ddp
early_stopping_patience: 150

inference_batch_size: 128

embedding_dimension: 128

standardize: false
prior_model: Atomref

lr: 0.0004
lr_factor: 0.8
lr_min: 1.0e-07
lr_patience: 15
lr_warmup_steps: 10000
max_num_neighbors: 32
max_z: 100
model: equivariant-transformer
neighbor_embedding: true

ngpus: 0

num_epochs: 3000
num_heads: 8
num_layers: 6
num_nodes: 1
num_rbf: 64
num_workers: 6
output_model: Scalar
precision: 32
rbf_type: expnorm
redirect: false
reduce_op: add
save_interval: 10
splits: null
test_interval: 3000
test_size: 0.1
train_size: 0.8
trainable_rbf: false
val_size: 0.1
weight_decay: 0.0